export const siteConfig = {
  name: "The Farmer's Kitchen",
  shortName: 'TFK',
  tagline: 'Authentic Flavors. Memorable Moments.',
  description:
    "The Farmer's Kitchen Shirwal — Best multi-cuisine family restaurant on NH-48 Pune Bangalore Highway. Authentic Maharashtrian thali, Punjabi favorites, North Indian & Chinese dishes. Open daily 11 AM – 11 PM. 4.2★ Google Rating. Reserve your table today.",
  url: 'https://thefarmerskitchen.in',
  ogImage:
    'https://images.pexels.com/photos/9418616/pexels-photo-9418616.jpeg?auto=compress&cs=tinysrgb&w=1200',
  location: {
    city: 'Shirwal',
    state: 'Maharashtra',
    country: 'India',
    address: 'NH-48 Pune Bangalore Highway, Shirwal, Maharashtra 412801, India',
    region: 'Satara',
    postalCode: '412801',
    geo: { lat: 18.0595, lng: 74.0189 },
    mapQuery: "The Farmer's Kitchen Shirwal Maharashtra NH-48",
  },
  phone: {
    primary: '+91 88888 33676',
    secondary: '+91 90111 54531',
    primaryRaw: '918888833676',
    secondaryRaw: '919011154531',
  },
  email: 'hello@thefarmerskitchen.in',
  rating: 4.2,
  reviewCount: 1700,
  costForTwo: 800,
  currency: 'INR',
  hours: {
    open: '11:00 AM',
    close: '11:00 PM',
    days: 'Mon – Sun',
    schema: 'Mo-Su 11:00-23:00',
  },
  cuisines: [
    'Maharashtrian',
    'Punjabi',
    'North Indian',
    'Chinese',
    'Multi-Cuisine',
  ],
  type: 'Premium Multi-Cuisine Family Dining Restaurant',
  social: {
    instagram: 'https://www.instagram.com/_thefarmerskitchen_?igsh=MWZyOHM1YXlsbG9peA==',
    facebook: 'https://facebook.com/thefarmerskitchen',
    youtube: 'https://youtube.com',
    twitter: 'https://twitter.com/thefarmerskitchen',
  },
  keywords: [
    'Restaurant in Shirwal',
    'Best Restaurant in Shirwal',
    'Family Restaurant Shirwal',
    'Maharashtrian Restaurant Shirwal',
    'Maharashtrian Thali Shirwal',
    'Punjabi Restaurant Shirwal',
    'Chinese Restaurant Shirwal',
    'Multi Cuisine Restaurant Shirwal',
    "The Farmer's Kitchen Shirwal",
    'Best Food in Shirwal',
    'Shirwal Family Dining',
    'Food Near Shirwal Highway',
    'Best Dining Experience Shirwal',
    'Restaurant Near Pune Bangalore Highway',
    'NH-48 Restaurant',
    'Pure Veg Restaurant Shirwal',
    'Non Veg Restaurant Shirwal',
    'Highway Dhaba Maharashtra',
    'Restaurant Near Satara',
    'Restaurant Near Karad',
    'Budget Restaurant Shirwal',
    'Premium Family Restaurant Maharashtra',
  ],
} as const;

export type SiteConfig = typeof siteConfig;
